language: python
python:
 - '2.7.10'
 - '3.5'
install:
 - pip install .
 - pip install coveralls
# - pip install -r requirements.txt
script:
 - nosetests --with-coverage --cover-package=PerfectNS test_PerfectNS/tests.py
after_success:
 - coveralls
